### ISSUE TITLE
Parfois le ocntenu dépasse, déborde sur une autre page puis génère une page quasi blanche, comment optimiser pour que le nombre d'articles défini soit garanti de tenir sur une page. Réduire font ? Réduire espacement entre les lignes? réduire même taille ds photos légèrement ?

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/pdf-exports#4]
on est obligé de refaire le template ?

**Comment by mikael-desharnais** [comment]
il faut reprendre le travail avec le graphiste et lui faire réaliser une intégration en prenant en compte le "worst case scenario" plutot qu'un cas facile à intégrer. Cela permettra ensuite d'intégrer les solutions trouvées dans le template. SInon, on fera de la recherche de solution à l'aveuglette

**Comment by thibaultvanc** [comment]
Le graphiste , qui n'en est pas un ne le refera pas. Le salon Playtime est samedi et schlomi me demande de faire les changements suivants : 
- reduire la hauteur ligne
- reduire Taille police  => mais une font-weight juste au dessus pour pa perdre en visibilité
- reduire Mages hautes / basses
