### ISSUE TITLE
detail de typo

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/pdf-exports#5]
![image](https://cloud.githubusercontent.com/assets/10731886/22333393/4795b318-e3d6-11e6-8046-722ec4c5387e.png)

**Comment by mikael-desharnais** [comment]
DOMPDF ne supporte pas les niveau de gras intermédiaire donc ce sera soit gras soit normal

**Comment by thibaultvanc** [comment]
Donc normal
