### ISSUE TITLE
PDF order shippment : erreur sur le seeder de Ludovic

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/pdf-exports#7]
![pasted image at 2017_01_26 03_06 pm](https://cloud.githubusercontent.com/assets/10731886/22334195/1cf1407e-e3da-11e6-8d78-b1c94bce033f.png)

**Comment by thibaultvanc** [comment]
sur le seeder

**Comment by mikael-desharnais** [comment]
Ok corrigé et pushé sur master
